[package]
name = "levm"
version.workspace = true
edition.workspace = true

[dependencies]
ethereum-types.workspace = true
bytes.workspace = true
sha3 = "0.10.8"
sha2 = "0.10.8"

[dev-dependencies]
hex = "0.4.3"
