# Runs the specified hive testing suites
name: Hive
on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.80.1

jobs:
  run-hive:
    name: ${{ matrix.simulation }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - simulation: rpc-compat

            run_command: just run-hive ethereum/rpc-compat "/${{ steps.testcases.outputs.content.split('\n').join('|') }}"
            file_path: .github/workflows/rpc-compat.txt
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Only if matrix has "file_path"
      - name: Read testcases from file
        if: ${{ matrix.file_path }}
        id: testcases
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ matrix.file_path }}

      - name: Download Hive
        run: just setup-hive

      - name: Run Hive Simulation
        run: ${{ matrix.run_command }}
